### ISSUE TITLE
Traceback (most recent call last) 

### ISSUE THREAD

**Issue by o-ze** [np1/mps#71]
File "/usr/bin/mps", line 7, in <module>
    from mps_pkg import main
  File "/usr/lib/python3.4/site-packages/mps_pkg/__init__.py", line 1, in <module>
    from . import main
  File "/usr/lib/python3.4/site-packages/mps_pkg/main.py", line 379, in <module>
    loadconfig(g.CFFILE)
  File "/usr/lib/python3.4/site-packages/mps_pkg/main.py", line 370, in loadconfig
    saved_config = pickle.load(open(pfile, "rb"))
EOFError: Ran out of input

**Comment by np1** [comment]
Hi, it seems the config file has become corrupt.
Try deleting it;
`rm ~/.config/mps/config`

**Comment by o-ze** [comment]
Thank you np1, didn't think it would be this easy.
