### ISSUE TITLE
Search for Russian strings on a system with koi8-r locale crashes mps

### ISSUE THREAD

**Issue by pitchforks** [np1/mps#72]
mps-0.20.16

locale is ru_RU.KOI8-R. yeah yeah, I know it's 2015 and everyone uses utf8

however, searching for something in Russian, crashes mps

traceback:

    Traceback (most recent call last):
      File "/usr/bin/mps", line 9, in <module>
        load_entry_point('mps==0.20.16', 'console_scripts', 'mps')()
      File "/usr/lib64/python2.7/site-packages/mps_pkg/main.py", line 2114, in main
        globals()[func](*matches)
      File "/usr/lib64/python2.7/site-packages/mps_pkg/main.py", line 1168, in search
        screen_update()
      File "/usr/lib64/python2.7/site-packages/mps_pkg/main.py", line 800, in screen_update
        xprint(g.message)
      File "/usr/lib64/python2.7/site-packages/mps_pkg/main.py", line 782, in xprint
        print(xenc(stuff), end=end)
      File "/usr/lib64/python2.7/site-packages/mps_pkg/main.py", line 787, in xenc
        stuff = utf8_replace(stuff) if not_utf8_environment else stuff
      File "/usr/lib64/python2.7/site-packages/mps_pkg/main.py", line 95, in utf8_replace
        txt = txt.encode(sse, "replace").decode("utf8", "ignore")
      File "/usr/lib64/python2.7/encodings/koi8_r.py", line 12, in encode
        return codecs.charmap_encode(input,errors,encoding_table)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xdb in position 20: ordinal not in range(128)

**Comment by np1** [comment]
Sorry, I don't know how to fix this :( Maybe one day I will learn. Until then, pull requests are welcome.

**Comment by pitchforks** [comment]
Sometimes it crashes for English search strings as well:

    .loft

The traceback:

    Traceback (most recent call last):
      File "/usr/bin/mps", line 9, in <module>
        load_entry_point('mps==0.20.16', 'console_scripts', 'mps')()
      File "/usr/lib64/python2.7/site-packages/mps_pkg/main.py", line 2127, in main
        screen_update()
      File "/usr/lib64/python2.7/site-packages/mps_pkg/main.py", line 797, in screen_update
        xprint(g.content)
      File "/usr/lib64/python2.7/site-packages/mps_pkg/main.py", line 782, in xprint
        print(xenc(stuff), end=end)
      File "/usr/lib64/python2.7/encodings/koi8_r.py", line 12, in encode
        return codecs.charmap_encode(input,errors,encoding_table)
    UnicodeEncodeError: 'charmap' codec can't encode character u'\u05e3' in position 1511: character maps to <undefined>
